version: '3.5'
networks:
  rabbitmq:
    external:
      name: rabbitmq

services:
  rabbitmq-node1:
    restart: always
    image: rabbitmq:3-management
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:
     - "15672:15672"
     - "5672:5672"
    networks:
      - rabbitmq
    environment:     
     - SERVICE_NAME=rabbitmq
     - SERVICE_TAGS=rabbitmq
     - SERVICE_REGION=DC1
     #- RABBITMQ_DEFAULT_USER=admin
     #- RABBITMQ_DEFAULT_PASS=Passw0rd
     #- RABBITMQ_DEFAULT_VHOST=/
     #- RABBITMQ_ERLANG_COOKIE='rabbitmq_secret_coookie'
     - RABBITMQ_NODENAME=rabbitmq@rabbitmq-node1
  rabbitmq-node2:
    restart: always
    image: rabbitmq:3-management
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:     
     - "5673:5673"
    networks:
      - rabbitmq
    environment:     
     - SERVICE_NAME=rabbitmq
     - SERVICE_TAGS=rabbitmq
     - SERVICE_REGION=DC1
     #- RABBITMQ_DEFAULT_USER=admin
     #- RABBITMQ_DEFAULT_PASS=Passw0rd
     #- RABBITMQ_ERLANG_COOKIE='rabbitmq_secret_coookie'
     #- RABBITMQ_DEFAULT_VHOST=/
     - RABBITMQ_NODENAME=rabbitmq@rabbitmq-node2
